# Generated by Django 4.2.29 on 2026-03-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ber', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ber', models.CharField(max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ber', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'متاح / Disponible'), ('rented', 'مؤجَّر / Loué'), ('maintenance', 'صيانة / Maintenance'), ('reserved', 'محجوز / Réservé'), ('retired', 'مسحوب / Retiré')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'جديد / Neuf'), ('excellent', 'ممتاز / Excellent'), ('good', 'جيد / Bon'), ('fair', 'مقبول / Passable'), ('damaged', 'تالف / Endommagé')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_period', models.CharField(choices=[('hour', 'ساعة / Heure'), ('day', 'يوم / Jour'), ('week', 'أسبوع / Semaine'), ('month', 'شهر / Mois')], default='day', max_length=10)),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_total', models.IntegerField(default=1)),
                ('quantity_available', models.IntegerField(default=1)),
                ('quantity_rented', models.IntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('era_period', models.CharField(blank=True, max_length=100)),
                ('storage_location', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_rentals', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('technician', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='items/thumbs/')),
                ('is_main', models.BooleanField(default=False)),
                ('caption_ar', models.CharField(blank=True, max_length=200)),
                ('caption_fr', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
        ),
    ]
