# Generated by Django 4.2.29 on 2026-03-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(choices=[('ar', 'AR'), ('ber', 'BER'), ('fr', 'FR'), ('en', 'EN')], default='ar', max_length=8)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('theatre_legal_name', models.CharField(default='Grand Theatre of Rabat', max_length=255)),
                ('theatre_rc', models.CharField(blank=True, max_length=64)),
                ('theatre_ice', models.CharField(blank=True, max_length=64)),
                ('theatre_if', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('legal_footer_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
