# Generated by Django 4.2.29 on 2026-03-11 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('association', 'Association'), ('government', 'Government Entity')], max_length=20)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('cin_document', models.FileField(blank=True, upload_to='docs/cin/')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('rc_number', models.CharField(blank=True, max_length=50)),
                ('ice_number', models.CharField(blank=True, max_length=15)),
                ('rc_document', models.FileField(blank=True, upload_to='docs/rc/')),
                ('association_name', models.CharField(blank=True, max_length=200)),
                ('association_license', models.CharField(blank=True, max_length=50)),
                ('license_document', models.FileField(blank=True, upload_to='docs/assoc/')),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('preferred_lang', models.CharField(default='ar', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
