# Generated by Django 4.2.29 on 2026-03-11 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('returned', models.BooleanField(default=False)),
                ('return_condition', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('decharge', 'Exit Voucher / Décharge'), ('reception', 'Receiving Voucher / Bon de Réception'), ('commande', 'Purchase Order / Bon de Commande'), ('pv', 'Handover Report / Procès-verbal')], max_length=20)),
                ('doc_number', models.CharField(max_length=30, unique=True)),
                ('external_name', models.CharField(max_length=200)),
                ('external_contact', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(through='documents.DocumentItem', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.externaldocument'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
    ]
