# Generated by Django 4.2.29 on 2026-03-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('individual', 'شخص طبيعي / Personne physique'), ('company', 'شركة / Société'), ('association', 'جمعية / Association'), ('government', 'هيئة حكومية / Organisme public'), ('foreign', 'جهة أجنبية / Entité étrangère')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('cin_or_rc', models.CharField(max_length=50, unique=True)),
                ('ice', models.CharField(blank=True, max_length=15)),
                ('if_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('nationality', models.CharField(default='Marocaine', max_length=100)),
                ('id_document', models.FileField(blank=True, upload_to='tenants/docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenants/photos/')),
                ('rating', models.CharField(choices=[('excellent', '⭐⭐⭐⭐⭐ ممتاز'), ('good', '⭐⭐⭐⭐ جيد'), ('average', '⭐⭐⭐ متوسط'), ('bad', '⭐ سيء')], default='good', max_length=20)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('total_contracts', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('preferred_language', models.CharField(default='ar', max_length=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
