# Generated by Django 4.2.29 on 2026-03-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=100)),
                ('damage_noted', models.TextField(blank=True)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=300)),
                ('event_type', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=300)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'مسودة / Brouillon'), ('pending', 'في الانتظار / En attente'), ('active', 'نشط / Actif'), ('completed', 'منتهي / Terminé'), ('cancelled', 'ملغى / Annulé'), ('overdue', 'متأخر / En retard'), ('disputed', 'متنازع عليه / Contesté')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('tva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_returned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقداً / Espèces'), ('check', 'شيك / Chèque'), ('transfer', 'تحويل / Virement'), ('card', 'بطاقة / Carte')], max_length=20)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('tenant_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('staff_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='ar', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(through='contracts.ContractItem', to='inventory.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('pdf_ar', models.FileField(blank=True, null=True, upload_to='invoices/ar/')),
                ('pdf_fr', models.FileField(blank=True, null=True, upload_to='invoices/fr/')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='invoices/en/')),
                ('pdf_ber', models.FileField(blank=True, null=True, upload_to='invoices/ber/')),
                ('qr_verification', models.CharField(max_length=200)),
                ('language', models.CharField(default='ar', max_length=5)),
                ('sent_to_tenant', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.rentalcontract')),
            ],
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.rentalcontract'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.rentalcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
