# Generated by Django 4.2.29 on 2026-03-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='venue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
