# Generated by Django 4.2.29 on 2026-03-14 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_rentalrequest_end_date_rentalrequest_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rental_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='staff_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة / Pending'), ('approved', 'مقبول / Approved'), ('rejected', 'مرفوض / Rejected')], default='pending', max_length=20),
        ),
    ]
